name: 'Whoop to Dropbox Sync'
description: 'Sync Whoop fitness data to Dropbox as Obsidian markdown notes'
author: 'MajorAaron'
branding:
  icon: 'activity'
  color: 'purple'

inputs:
  # Whoop OAuth credentials
  whoop_client_id:
    description: 'Whoop OAuth Client ID'
    required: true
  whoop_client_secret:
    description: 'Whoop OAuth Client Secret'
    required: true
  whoop_refresh_token:
    description: 'Whoop Refresh Token'
    required: true
  whoop_redirect_uri:
    description: 'Whoop OAuth Redirect URI'
    required: false
    default: 'http://localhost:3000/api/auth/callback'
  
  # Dropbox OAuth credentials
  dropbox_app_key:
    description: 'Dropbox App Key'
    required: true
  dropbox_app_secret:
    description: 'Dropbox App Secret'
    required: true
  dropbox_access_token:
    description: 'Dropbox Access Token'
    required: true
  dropbox_refresh_token:
    description: 'Dropbox Refresh Token'
    required: true
  
  # Sync configuration
  days_back:
    description: 'Number of days to sync (default: 7)'
    required: false
    default: '7'
  dropbox_path:
    description: 'Dropbox path for notes (default: /WHOOP)'
    required: false
    default: '/WHOOP'
  create_readme:
    description: 'Create README.md in Dropbox (default: true)'
    required: false
    default: 'true'
  debug:
    description: 'Enable debug logging (default: false)'
    required: false
    default: 'false'
  date_format:
    description: 'Date format for notes (default: YYYY-MM-DD)'
    required: false
    default: 'YYYY-MM-DD'

outputs:
  notes_created:
    description: 'Number of notes uploaded to Dropbox'
  new_refresh_token:
    description: 'New Whoop refresh token if it was updated (store this in your secrets)'
  new_dropbox_access_token:
    description: 'New Dropbox access token if refreshed'
  new_dropbox_refresh_token:
    description: 'New Dropbox refresh token if rotated'
  sync_summary:
    description: 'Summary of synced data'
  sleep_records:
    description: 'Number of sleep records synced'
  recovery_records:
    description: 'Number of recovery records synced'
  workout_records:
    description: 'Number of workout records synced'

runs:
  using: 'node20'
  main: 'src/index.js'