name: Sync Whoop Data to Obsidian

on:
  schedule:
    # Run daily at 6:15 AM UTC
    - cron: '15 6 * * *'
  workflow_dispatch:
    inputs:
      days_back:
        description: 'Number of days to sync'
        required: false
        default: '7'

permissions:
  contents: write
  actions: write
  secrets: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PA_TOKEN }}
        
      - name: Sync Whoop data
        id: whoop-sync
        uses: MajorAaron/whoop-obsidian-sync-action@main
        with:
          whoop_client_id: ${{ secrets.WHOOP_CLIENT_ID }}
          whoop_client_secret: ${{ secrets.WHOOP_CLIENT_SECRET }}
          whoop_refresh_token: ${{ secrets.WHOOP_REFRESH_TOKEN }}
          days_back: ${{ github.event.inputs.days_back || '7' }}
          output_path: 'WHOOP'
          create_readme: 'true'
          debug: 'false'
          
      - name: Update refresh token if rotated
        if: steps.whoop-sync.outputs.new_refresh_token
        env:
          GH_TOKEN: ${{ secrets.PA_TOKEN }}
        run: |
          echo "ðŸ”„ Refresh token was rotated, updating secret..."
          gh secret set WHOOP_REFRESH_TOKEN \
            --body "${{ steps.whoop-sync.outputs.new_refresh_token }}" \
            --repo ${{ github.repository }}
          echo "âœ… Refresh token updated successfully"
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes to commit
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Sync Whoop data - ${{ steps.whoop-sync.outputs.sync_summary || 'Daily sync' }}"
            git push
            echo "âœ… Changes committed and pushed"
          else
            echo "No changes to commit"
          fi
          
      - name: Summary
        if: always()
        run: |
          echo "## Whoop Sync Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.whoop-sync.outputs.notes_created }}" ]; then
            echo "ðŸ“ **Notes Created/Updated:** ${{ steps.whoop-sync.outputs.notes_created }}" >> $GITHUB_STEP_SUMMARY
            echo "ðŸ˜´ **Sleep Records:** ${{ steps.whoop-sync.outputs.sleep_records }}" >> $GITHUB_STEP_SUMMARY
            echo "ðŸ’ª **Recovery Records:** ${{ steps.whoop-sync.outputs.recovery_records }}" >> $GITHUB_STEP_SUMMARY
            echo "ðŸƒ **Workout Records:** ${{ steps.whoop-sync.outputs.workout_records }}" >> $GITHUB_STEP_SUMMARY
          fi
          if [ "${{ steps.whoop-sync.outputs.new_refresh_token }}" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "ðŸ”„ **Token Rotated:** Refresh token was automatically updated" >> $GITHUB_STEP_SUMMARY
          fi