name: Sync Whoop Data to Obsidian

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM
  workflow_dispatch:
    inputs:
      days_back:
        description: 'Number of days to sync'
        required: false
        default: '7'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PA_TOKEN || github.token }}
        
      - name: Sync Whoop data
        id: whoop-sync
        uses: MajorAaron/whoop-obsidian-sync-action@main
        with:
          whoop_client_id: ${{ secrets.WHOOP_CLIENT_ID }}
          whoop_client_secret: ${{ secrets.WHOOP_CLIENT_SECRET }}
          whoop_refresh_token: ${{ secrets.WHOOP_REFRESH_TOKEN }}
          whoop_redirect_uri: 'http://localhost:3000/api/auth/callback'
          days_back: ${{ github.event.inputs.days_back || '7' }}
          output_path: 'WHOOP'
          create_readme: 'true'
          debug: 'false'
          
      - name: Update refresh token if rotated
        if: steps.whoop-sync.outputs.new_refresh_token \!= ''
        env:
          GH_TOKEN: ${{ secrets.PA_TOKEN }}
        run: |
          echo "🔄 Refresh token was rotated, updating secret..."
          gh secret set WHOOP_REFRESH_TOKEN \
            --body "${{ steps.whoop-sync.outputs.new_refresh_token }}" \
            --repo ${{ github.repository }}
          echo "✅ Refresh token updated successfully"
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes to commit
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Sync Whoop data - ${{ steps.whoop-sync.outputs.sync_summary || 'Daily sync' }}"
            git push
            echo "✅ Changes committed and pushed"
          else
            echo "No changes to commit"
          fi
