name: Sync Whoop to THE MAINFRAME

on:
  schedule:
    # Run daily at 6:00 AM UTC (1:00 AM EST / 2:00 AM EDT)
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      days_back:
        description: 'Number of days to sync (default: 7)'
        required: false
        default: '7'
        type: string
      start_date:
        description: 'Start date (YYYY-MM-DD) - overrides days_back'
        required: false
        type: string
      end_date:
        description: 'End date (YYYY-MM-DD) - overrides days_back'
        required: false
        type: string

jobs:
  sync-whoop-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout sync action
        uses: actions/checkout@v4
        with:
          path: sync-action
      
      - name: Checkout THE MAINFRAME
        uses: actions/checkout@v4
        with:
          repository: MajorAaron/THE-MAINFRAME
          token: ${{ secrets.PA_TOKEN }}
          path: mainframe
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        working-directory: sync-action
        run: npm install
      
      - name: Sync Whoop Data
        id: whoop-sync
        working-directory: sync-action
        env:
          WHOOP_CLIENT_ID: ${{ secrets.WHOOP_CLIENT_ID }}
          WHOOP_CLIENT_SECRET: ${{ secrets.WHOOP_CLIENT_SECRET }}
          WHOOP_REFRESH_TOKEN: ${{ secrets.WHOOP_REFRESH_TOKEN }}
          WHOOP_REDIRECT_URI: ${{ secrets.WHOOP_REDIRECT_URI || 'http://localhost:3000/api/auth/callback' }}
          OUTPUT_PATH: ../mainframe
          DAYS_BACK: ${{ github.event.inputs.days_back || '7' }}
          START_DATE: ${{ github.event.inputs.start_date }}
          END_DATE: ${{ github.event.inputs.end_date }}
        run: node src/index.js
      
      - name: Update refresh token if rotated
        if: steps.whoop-sync.outputs.new_refresh_token != ''
        env:
          GH_TOKEN: ${{ secrets.PA_TOKEN }}
        run: |
          gh secret set WHOOP_REFRESH_TOKEN \
            --body "${{ steps.whoop-sync.outputs.new_refresh_token }}" \
            --repo ${{ github.repository }}
      
      - name: Commit and push changes to THE MAINFRAME
        working-directory: mainframe
        run: |
          git config user.name "Whoop Sync Bot"
          git config user.email "action@github.com"
          
          # Check if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Whoop data sync - $(date +'%Y-%m-%d')"
            git push
            echo "✅ Changes pushed to THE MAINFRAME"
          else
            echo "📝 No changes to commit"
          fi